import turtle
"""
def testdrive():
    turtle.bgcolor("pink")
    turtle.pencolor("red")
    turtle.forward(100)
    turtle.left(87)
    turtle.setheading(127)
    turtle.up()
    turtle.down()
    turtle.goto(50,50)
    turtle.home()
    turtle.circle(25)
    turtle.done()
    
def turtle_state():
    turtle.isdown()
    turtle.heading()
    print(turtle.xcor())
    print(turtle.ycor())  

def main():
    turtle_state()
    testdrive()
    turtle_state()

main()

def square():
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(100)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(75)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(25)
    turtle.done()

#2.3.8
def square():
    turtle.left(45)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(75)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(25)
    turtle.left(90)
    turtle.forward(25)
    turtle.done()
"""
def circle():
    turtle.pencolor("red")
    turtle.fillcolor("pink")
    turtle.begin_fill()
    turtle.circle(25)
    turtle.end_fill()
                
def main():
    circle()
    
    
main()
